apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: product-api
  description: The product API
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: experimental
  owner: product-team
  definition:
    $text: ./product.oas.yaml