apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: aws-team
  description: The infra department
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: infrastructure
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sourabh.aws
spec:
  profile:
    # Intentional no displayName for testing
    email: sourabh@acme.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [aws-team]

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: janelle.dawe.aws
spec:
  profile:
    displayName: Janelle Dawe
    email: janelle-dawe@example.com
    picture: https://avatars.dicebear.com/api/avataaars/janelle-dawe@example.com.svg?background=%23fff
  memberOf: [aws-team]