apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: product-team
  description: Product Team
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: website-group
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nigel.manning.product
spec:
  profile:
    displayName: Nigel Manning
    email: nigel-manning@example.com
    picture: https://avatars.dicebear.com/api/avataaars/nigel-manning@example.com.svg?background=%23fff
  memberOf: [product-team]