apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: Test.Vault
namespace: dev
bases:
  - ../../base
commonAnnotations:
  app: Test.Vault
  backstage.io/kubernetes-id: "Test.Vault"
commonLabels:
  app: Test.Vault
  backstage.io/kubernetes-id: "Test.Vault"
patchesStrategicMerge:
  - configmap_patch.yaml
  - deployment_patch.yaml